### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#1]
## User Story
As a developer, when the page loads I should see a bg color, the word HI, and a button.

## Acceptance Criteria
**WHEN** the page loads
**THEN** the background color should be pink
**AND** there should be a LARGE "hi"
**AND** there should be a console.log that says "project"
**AND** there should be red bootstrap button that says "button"

## Development
- index.html - with boilerplate html, script tag for main.js and a link tag for main.css, need an h1 tag - with "hi", and a bootstrap button with btn-danger class
- main.js - with a console.log
- main.css - with background color change on the body
- Add link and script tags for bootstrap

**Comment by westmary48** [comment]
Get bootstrap CSS and JS here: https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by zoeames** [comment]
👍
