### ISSUE TITLE
Beer Data

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#10]
## User Story
As a developer, I should see an array of objects for the beer data 

Acceptance Criteria
WHEN I look at my javascript file
THEN I should see an array of objects for my buy beer page

Development
- create an array called beer
- add 6 objects for each piece of merchanise
- OBJECT EXAMPLE key value pairs
Title: Vintage T Shirt
Image: picture of item
Merchandise: Shirt
Price: $20

**Comment by zoeames** [comment]
👍
