### ISSUE TITLE
buyBeerCardBuilder

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#11]
## User Story
As a user, when the page loads, I should see 6 cards for each item with title, image, price, description, and an add button

## Acceptance Criteria
WHEN the page loads
THEN four cards should display to the dom

## Development
- create a buyBeerCardBuilder function
- create a domString
- let domString = ' '
- add a forEachLoop
- add bootstrap card from comments in previous ticket
use the div id (Buy Beer PAGE id = "beer" )
- add a footer in the domString
- create a Add button
- add a class to the button called `addBtn`
- call printToDom function and pass in divId and domstring
- call the buyBeerCardBuilder in the `init` function

**Comment by westmary48** [comment]
Add footer and button to the bottom
Link - https://getbootstrap.com/docs/4.1/components/card/

```html
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src=".../100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```

**Comment by zoeames** [comment]
👍

**Comment by westmary48** [comment]
**WIREFRAME**
<img width="694" alt="Screen Shot 2019-03-30 at 9 54 54 AM" src="https://user-images.githubusercontent.com/42101883/55277800-26424d80-52d2-11e9-9a31-95861132c590.png">
