### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#12]
## User Story

As a user, I should see a footer that includes a social media link, the address, and phone number at the bottom of the page on page load.

## Acceptance Criteria
**WHEN** the page loads, 
**THEN** I should see a footer at the bottom of the page

## Development
- add footer a footer tag at the end of the page that has a class `page-footer` in your HTML File
- add social media logos, address, and phone number to the footer

**Comment by zoeames** [comment]
👍
