### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#2]
## User Story
As a user when the page loads, I should see a nav bar with links to each page, the logo, and the footer. 

## Acceptance Criteria
**WHEN** the page loads 
**THEN** I should see a navbar with links to each page ( Home, Brew Masters, Events, Buy Beers)
**AND** I should see the logo listed above the navbar
**AND** I should see Howling Oats Brewery in the body
**AND** I should see the footer at the bottom of the page ( has address, social media, and phone number)

## Development
- Add an `<img tag>` for the logo - go on google and find a good logo - add a class = `logo`
- add bootstrap navbar to HTML ( in the comments) - add class = `navBar` id= `navId`
- NAVBAR
- add div with a class = "navBar"
- add ul with an id = "navLinks"
- add li and an a tag for each link
- each li tag should have an individual id
- HOME id = `navTohome` 
- BREW MASTERS id = `navToBrew`
- EVENTS id = `navToEvents`
- BUY BEERS = id `navToBuy`
- In the body h1 tag that says Howling Oats Brewery

**Comment by zoeames** [comment]
make a separate ticket for the footer

**Comment by zoeames** [comment]
Add a link to the bootstrap navbar to this ticket

**Comment by okaformark** [comment]
![image](https://user-images.githubusercontent.com/38026989/55277831-5689ec00-52d2-11e9-9a00-29f7f57749ff.png)

**Comment by zoeames** [comment]
👍
