### ISSUE TITLE
Click Events for Navbar

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#3]
## User Story
As a user, when I click any link on the navbar, it should direct me to the page that I selected.

## Acceptance Criteria
**WHEN** I click any link on the navbar
**THEN** the click event should take me to my desired page

## Development
- Create a function called `navEvents`
- In this function we will have 4 event listeners that have each nav id associated with it
- then we add an e.prevent default below the event listener
- in HTML body add a div to each page and add an id with a class = `hideStuff` in each div
- HOME PAGE - id = "home" class = `hideStuff`
- BREW PAGE id = "brewMasters" class = `hideStuff`
- EVENTS PAGE id = "Events" class = `hideStuff`
-BUY BEER PAGE id = "buyBeer" class = `hideStuff`
- then we will add  4 document.getElementById under the prevent default for each page and put in their individual page id
- then we will add classList.add('hideStuff') for the pages we want to hide ( all pages but the one we clicked on in the event listener)
- Then we will add classList.remove('hideStuff') for the one we want to show
- target the class `hideStuff` in main.css
- and add a display: none important!
- add an `init` function and call the `navEvents` function inside
- call the `init` function at the bottom of the page

**Comment by zoeames** [comment]
👍
