### ISSUE TITLE
Nav Bar Form

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#5]
## User Story
As a user, when I enter my name and email in the form and click the submit button, I should receive an alert stating that 'my email has been received'.

## Acceptance Criteria 
** WHEN** the page loads, there should be a form with an input for a name and email and submit button
** AND** when I type in my information and hit the button
** THEN** I should receive an alert that says 'email has been received'
**AND** the input text should be cleared out

## Development
- Add a form in HTML with two input fields and a Submit button
- add ids to the inputs 
- name input id = `nameInput`
- email input id = `emailInput`
- Add an id in HTML to the submit button id= `submitButton`
- Add a function called `submitEvent`
- Add an eventListener in the `submitEvent` function 
- add an alert that says `email has been received`
- call the `clearFormInput`  
- create function called `clearFormInput` that selects the input ids and set the value to the empty string.
- call the `submitButton` function in the `init` function
- replace the bootstrap ids in the example below with our ids

**Comment by westmary48** [comment]
```html
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

**Comment by zoeames** [comment]
👍
