### ISSUE TITLE
Brew Masters Data

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#6]
## User Story
As a developer, I should see an array of objects for the brew masters data

## Acceptance Criteria
**WHEN** I look at my javascript file
**THEN** I should see an array of objects for my brew masters page

## Development
- create an array called brewMasters
- add 4 objects for each member
OBJECT EXAMPLE key value pairs
- Name: Mary
- Image: be sure to alt  url('')
- Description: short bio
- gitHub link: # github 
- each group member will submit information for the values and the key value pairs
- each image we submit add a description about the image in the alt

**Comment by zoeames** [comment]
👍
