### ISSUE TITLE
Events Data

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#8]
## User Story
As a developer, I should see an array of objects for the event data and a complex data structure for the attendees key value pair

## Acceptance Criteria
WHEN I look at my javascript file
THEN I should see an array of objects for my events page

## Development
- create an array called events
- add 4 objects for each event
OBJECT EXAMPLE key value pairs
Name: Mary
Image: picture of place
Date: 4/3/2019
Address: 123 Main Street
Attendees: [ Mary, Sarah, Mark, and Daniel]

**Comment by zoeames** [comment]
👍
