### ISSUE TITLE
eventsCardBuilder

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-9/foundations-group-project-howling-oats#9]
## User Story
As a user, when the page loads, I should see 4 cards for each event with title, image, address, date, description, alt text, attendees.

## Acceptance Criteria
**WHEN** the page loads
**THEN** four cards should display to the dom

## Development
- create a `eventsCardBuilder` function
- create a domString
- let domString = ' '
- add a forEachLoop
- nest a forEach loop within the loop for the complex data in the attendees array
- add bootstrap card from comments in previous ticket
- use the div id (Events PAGE id = "events" )
- call printToDom function and pass in divId and domstring
- call the eventsCardBuilder in the `init` function

**Comment by zoeames** [comment]
👍

**Comment by westmary48** [comment]
**WIREFRAME**
<img width="669" alt="Screen Shot 2019-03-30 at 9 35 49 AM" src="https://user-images.githubusercontent.com/42101883/55277565-b3d06e00-52cf-11e9-94f0-3072655ad6df.png">
